### ISSUE TITLE
Ability to continued skip the silent parts of video

### ISSUE THREAD

**Issue by song2daodao** [detuur/mpv-scripts#10]
Like the "skip silence" browser extension or Just player, it would be awesome if the script have the ability to skip the silence part of video. In many online class videos, the silent parts are totally waste of time.
The silent skip function of newpie and justpalyer is very powerful, but unfortunately they only available on Android. After a lot of searching it seems that only your script can provide this feature to mpv. Please consider upgrade the script with this feature, it would be very useful !!

**Comment by detuur** [comment]
Thank you for the kind words. I don't currently have time to write something like that, but I am aware of this script: https://gist.github.com/bitingsock/e8a56446ad9c1ed92d872aeb38edf124

It might just fit your use case. Otherwise, the functionality shouldn't be too hard for a newbie Lua programmer to adapt from my script. Good luck!

**Comment by song2daodao** [comment]
> Thank you for the kind words. I don't currently have time to write something like that, but I am aware of this script: https://gist.github.com/bitingsock/e8a56446ad9c1ed92d872aeb38edf124
> 
> It might just fit your use case. Otherwise, the functionality shouldn't be too hard for a newbie Lua programmer to adapt from my script. Good luck!

Thanks！！
